cadc-tap:
  tapSchema:
    image:
      repository: "lsstsqre/tap-schema-usdf-prod-tap"

  config:
    backend: "pg"
    # pg:
    #   host: "10.0.1.74:5433"
    #   database: "RSPtest"
    #   username: "rspDev"
    gcsBucket: "minio-tap"
    gcsBucketUrl: "http://minio.local:9000"
    gcsBucketType: "S3"
