cadc-tap:
  tapSchema:
    image:
      repository: "stvoutsin/tap-schema-roe"

  config:
    backend: "postgres"
    gcsBucket: "minio-tap"
    gcsBucketUrl: "http://minio.local:9000"
    gcsBucketType: "S3"
